# Generated by Django 5.0.7 on 2024-08-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Color_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
