# Generated by Django 5.0.7 on 2024-08-06 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Color_app', '0002_tbl_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_id', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='white', max_length=20)),
                ('combined_color', models.CharField(default='white', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_color',
        ),
        migrations.DeleteModel(
            name='tbl_register',
        ),
    ]
