# Generated by Django 5.0.7 on 2024-08-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Color_app', '0005_container_delete_tbl_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='container',
            name='combined_color',
            field=models.CharField(blank=True, default='white', max_length=50),
        ),
        migrations.AlterField(
            model_name='container',
            name='div_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
